# developにpush時、自動でphase2にマージ
name: Merge to phase2

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  merge_to_phase2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #  phase2に移動 > developをマージし、変更をphase2ブランチにプッシュ
      - name: Merge to phase2
        run: |
          git config --global user.email "t.w11129313@gmail.com"
          git config --global user.name "takumanabe"
          git fetch origin phase2:phase2
          git checkout phase2
          git merge -X ours develop --no-ff --no-edit --allow-unrelated-histories
          git push origin phase2
