name: Merge to phase2

on:
  push:
    branches:
      - develop

jobs:
  merge_to_phase2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to phase2
        run: |
          git checkout phase2
          git merge develop --no-ff --no-edit
          git push origin phase2
